#ifndef ICEAVGLUMFINDOBJECTPROCDEF_H
#define ICEAVGLUMFINDOBJECTPROCDEF_H

#include <QtCore/qglobal.h>

#ifndef ICEAVGLUMFINDOBJECTPROC_DECL_EXPORT
#   ifdef Q_OS_WIN
#       define ICEAVGLUMFINDOBJECTPROC_DECL_EXPORT __declspec(dllexport)
#   else
#       define ICEAVGLUMFINDOBJECTPROC_DECL_EXPORT
#   endif
#endif

#ifndef ICEAVGLUMFINDOBJECTPROC_DECL_IMPORT
#   if defined(Q_OS_WIN)
#       define ICEAVGLUMFINDOBJECTPROC_DECL_IMPORT __declspec(dllimport)
#   else
#       define ICEAVGLUMFINDOBJECTPROC_DECL_IMPORT
#   endif
#endif

#ifdef BUILD_ICEAVGLUMFINDOBJECTPROC_DLL
#   define ICEAVGLUMFINDOBJECTPROC_EXPORT ICEAVGLUMFINDOBJECTPROC_DECL_EXPORT
#else
#   define ICEAVGLUMFINDOBJECTPROC_EXPORT ICEAVGLUMFINDOBJECTPROC_DECL_IMPORT
#endif

#pragma warning( disable : 4290 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4505 )

#endif // ICEAVGLUMFINDOBJECTPROCDEF_H
