#ifndef ICEAVGCOLORFINDOBJECTPROCDEF_H
#define ICEAVGCOLORFINDOBJECTPROCDEF_H

#include <QtCore/qglobal.h>

#ifndef ICEAVGCOLORFINDOBJECTPROC_DECL_EXPORT
#   ifdef Q_OS_WIN
#       define ICEAVGCOLORFINDOBJECTPROC_DECL_EXPORT __declspec(dllexport)
#   else
#       define ICEAVGCOLORFINDOBJECTPROC_DECL_EXPORT
#   endif
#endif

#ifndef ICEAVGCOLORFINDOBJECTPROC_DECL_IMPORT
#   if defined(Q_OS_WIN)
#       define ICEAVGCOLORFINDOBJECTPROC_DECL_IMPORT __declspec(dllimport)
#   else
#       define ICEAVGCOLORFINDOBJECTPROC_DECL_IMPORT
#   endif
#endif

#ifdef BUILD_ICEAVGCOLORFINDOBJECTPROC_DLL
#   define ICEAVGCOLORFINDOBJECTPROC_EXPORT ICEAVGCOLORFINDOBJECTPROC_DECL_EXPORT
#else
#   define ICEAVGCOLORFINDOBJECTPROC_EXPORT ICEAVGCOLORFINDOBJECTPROC_DECL_IMPORT
#endif

#pragma warning( disable : 4290 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4505 )

#endif // ICEAVGCOLORFINDOBJECTPROCDEF_H
